version: '3.4'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/images
      POSTGRES_USER: images
      POSTGRES_PASSWORD: images
      POSTGRES_DB: api_images
