# Generated by Django 4.2.5 on 2023-09-25 20:04

from django.db import migrations, models

import image.handlers
import image.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpiringLinkAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Link (genereted automatically)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expiration_time",
                    models.IntegerField(
                        validators=[image.validators.validate_expiration_time],
                        verbose_name="Expiration time (in seconds)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        null=True, upload_to=image.handlers.thumbnail_path_handler
                    ),
                ),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ThumbnailType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField(verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=image.handlers.image_path_handler),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
