# Generated by Django 4.2.5 on 2023-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.ImageField(upload_to="", verbose_name=models.Model)),
                ("height", models.ImageField(upload_to="", verbose_name=models.Model)),
            ],
        ),
    ]
